export const uiText = {
  appName: "NowTune",
  metadata: {
    title: "NowTune | 音楽アクティビティSNS",
    description: "音楽好きが投稿とリスニング状況を共有するタイムラインSNS。",
  },
  nav: {
    timeline: "タイムライン",
    post: "投稿",
    listening: "リスニング",
    profile: "プロフィール",
  },
  common: {
    openTrack: "トラックを開く",
    commentReady: "コメントを見る",
    soon: "近日対応",
    postBadge: "投稿",
    listeningBadge: "リスニング",
    profileBadge: "プロフィール",
  },
  timeline: {
    label: "タイムライン",
    title: "NowTuneフィード",
    description:
      "フォロー中のユーザーの投稿とリスニング更新が混ざったフィードです。タブで投稿かリスニングのみを絞り込めます。",
    highlights: [
      "投稿＋リスニング更新",
      "いいね・フォローは次のステップで実装",
    ],
    filters: {
      all: "すべて",
      post: "投稿",
      listening: "リスニング",
    },
    activityTitle: "アクティビティ",
    activityDescription: "投稿とリスニングのミックスフィード",
    quickActionsTitle: "クイックアクション",
    quickActionsDescription: "投稿作成やリスニング開始、プロフィール設定を進めましょう。",
    quickActions: [
      {
        title: "投稿する",
        description: "トラックを選び、コメントを添えてタイムラインにシェア。",
        badge: "投稿",
      },
      {
        title: "リスニング開始",
        description: "いま再生している曲をワンタップで共有。",
        badge: "リスニング",
      },
      {
        title: "プロフィールを整える",
        description: "表示名やアバター、ひとこと自己紹介をセット。",
        badge: "プロフィール",
      },
    ],
    profileCardTitle: "あなた",
    profileCardDescription:
      "プロフィールでは投稿、最近のリスニング、フォロー状況を表示します。Supabase認証とデータ連携で仕上げましょう。",
    following: "フォロー中",
    followers: "フォロワー",
  },
  listening: {
    label: "リスニング",
    title: "リスニングの開始・停止",
    description:
      "`/api/listening/start` と `/api/listening/stop` に対応するフォームです。アクティブな曲を記録し、以前のセッションを終了させます。",
    currentSessionTitle: "現在のセッション",
    currentSessionDescription: "同時にアクティブなのは1件のみ。",
    form: {
      title: "タイトル",
      artist: "アーティスト",
      service: "サービス",
      url: "トラックURL",
      start: "リスニング開始",
      stop: "停止",
      hint: "開始すると前のセッションを終了し、開始/終了時刻を記録します。",
    },
    previewTitle: "タイムラインプレビュー",
    checklistTitle: "エンドポイントチェックリスト",
    checklist: [
      "POST `/api/listening/start` – 新規アクティビティ作成",
      "POST `/api/listening/stop` – アクティブ行の `ended_at` を更新",
      "ユーザーごとに同時アクティブは1件のみ",
    ],
    statusListening: "再生中",
    statusStopped: "停止中",
  },
  post: {
    label: "投稿作成",
    title: "トラックをコメント付きで共有",
    description:
      "投稿はトラックと感想のセットです。入力した内容を `/api/posts` に渡してタイムラインへ公開しましょう。",
    trackSectionTitle: "トラック",
    trackSectionDescription: "手入力またはURLから作成できます。",
    apiReady: "API準備済み",
    field: {
      title: "タイトル",
      artist: "アーティスト",
      service: "サービス",
      url: "トラックURL",
      titlePlaceholder: "ネオン・スカイライン",
      artistPlaceholder: "シブヤ・エコー",
      urlPlaceholder: "https://...",
      comment: "コメント",
      commentPlaceholder: "どんな気分？なぜこの曲？",
    },
    submitHint: "投稿とトラック作成をまとめて実行します。",
    saveDraft: "下書きを保存",
    message: "投稿の準備ができました！APIと接続してタイムラインへ公開してください。",
    previewLabel: "プレビュー",
    previewTitle: "タイムラインカード",
    howToTitle: "接続の手順",
    howToSteps: [
      "`/api/posts` にトラック情報または `track_id` を送信",
      "入力されたトラックが新規の場合は先にトラック作成",
      "作成した投稿をユーザーとトラック情報付きで返却",
    ],
    fallbackTitle: "タイトル未設定",
    fallbackArtist: "アーティスト未設定",
  },
  profile: {
    label: "プロフィール",
    follow: "フォロー",
    recentPosts: "最近の投稿",
    recentPostsDescription: "`/api/posts` の内容を埋め込み表示",
    listeningHistory: "リスニング履歴",
    apiWiringTitle: "API連携メモ",
    apiWiringItems: [
      "GET `/api/users/:id` – ユーザー情報と投稿/リスニング",
      "POST `/api/users/:id/follow` – フォロー切り替え",
      "タイムラインと同じカードUIを再利用",
    ],
    live: "ライブ中",
    ended: "終了",
    commentReady: "コメントを見る",
  },
} as const;

export type UiText = typeof uiText;
